<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4Uu6lUw' shared service.

return $this->privates['.service_locator.4Uu6lUw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('twig' => function () {
    return ($this->services['twig'] ?? $this->load('getTwigService.php'));
}));
