<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKSbWlhq\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKSbWlhq/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKSbWlhq.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerKSbWlhq\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerKSbWlhq\srcProdProjectContainer(array(
    'container.build_hash' => 'KSbWlhq',
    'container.build_id' => '89701b68',
    'container.build_time' => 1548935065,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKSbWlhq');
