<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6PjTQAv\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6PjTQAv/srcProdProjectContainer.php') {
    touch(__DIR__.'/Container6PjTQAv.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\Container6PjTQAv\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \Container6PjTQAv\srcProdProjectContainer(array(
    'container.build_hash' => '6PjTQAv',
    'container.build_id' => '34c51411',
    'container.build_time' => 1549462874,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6PjTQAv');
