<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRzGqoF8\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRzGqoF8/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRzGqoF8.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerRzGqoF8\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerRzGqoF8\srcProdProjectContainer(array(
    'container.build_hash' => 'RzGqoF8',
    'container.build_id' => '1b23aa78',
    'container.build_time' => 1548272609,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRzGqoF8');
