index:
    path: /
    controller: App\Controller\DefaultController::index
contact:
    path: /contact
    controller: App\Controller\DefaultController::contact
competences:
    path: /formations
    controller: App\Controller\DefaultController::formations
experiences:
    path: /experiences
    controller: App\Controller\DefaultController::experiences
projets:
    path: /projets
    controller: App\Controller\DefaultController::projets
dlcv:
    path: /dlcv
    controller: App\Controller\DefaultController::dlcv
