<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\DefaultController::competences' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController::contact' => function () {
    return ($this->privates['.service_locator.CMQS5Kb'] ?? $this->load('get_ServiceLocator_CMQS5KbService.php'));
}, 'App\\Controller\\DefaultController::experiences' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController::index' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController::projets' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController:competences' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController:contact' => function () {
    return ($this->privates['.service_locator.CMQS5Kb'] ?? $this->load('get_ServiceLocator_CMQS5KbService.php'));
}, 'App\\Controller\\DefaultController:experiences' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController:index' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
}, 'App\\Controller\\DefaultController:projets' => function () {
    return ($this->privates['.service_locator.4Uu6lUw'] ?? $this->load('get_ServiceLocator_4Uu6lUwService.php'));
})));
