<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW6v8Xtr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW6v8Xtr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerW6v8Xtr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerW6v8Xtr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerW6v8Xtr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'W6v8Xtr',
    'container.build_id' => 'a05875e1',
    'container.build_time' => 1538067867,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerW6v8Xtr');
