<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ1KDKXX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ1KDKXX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ1KDKXX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ1KDKXX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJ1KDKXX\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'J1KDKXX',
    'container.build_id' => '7a884ae3',
    'container.build_time' => 1547046157,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ1KDKXX');
